/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteersRouteImport } from './routes/volunteers'
import { Route as VillagesRouteImport } from './routes/villages'
import { Route as TqiReportsRouteImport } from './routes/tqi-reports'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as PanchayatsRouteImport } from './routes/panchayats'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeworkRouteImport } from './routes/homework'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as ClusterDashboardRouteImport } from './routes/cluster-dashboard'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AdvanceRouteImport } from './routes/advance'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as AcademicYearsRouteImport } from './routes/academic-years'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TqiReportsIndexRouteImport } from './routes/tqi-reports/index'
import { Route as TqiReportsCreateRouteImport } from './routes/tqi-reports/create'
import { Route as AttendanceVolunteersRouteImport } from './routes/attendance/volunteers'
import { Route as AttendanceStudentsRouteImport } from './routes/attendance/students'
import { Route as AttendanceHomeworkRouteImport } from './routes/attendance/homework'
import { Route as AttendanceHistoryRouteImport } from './routes/attendance/history'
import { Route as AttendanceAnalyticsRouteImport } from './routes/attendance/analytics'

const VolunteersRoute = VolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const VillagesRoute = VillagesRouteImport.update({
  id: '/villages',
  path: '/villages',
  getParentRoute: () => rootRouteImport,
} as any)
const TqiReportsRoute = TqiReportsRouteImport.update({
  id: '/tqi-reports',
  path: '/tqi-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const PanchayatsRoute = PanchayatsRouteImport.update({
  id: '/panchayats',
  path: '/panchayats',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkRoute = HomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterDashboardRoute = ClusterDashboardRouteImport.update({
  id: '/cluster-dashboard',
  path: '/cluster-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvanceRoute = AdvanceRouteImport.update({
  id: '/advance',
  path: '/advance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicYearsRoute = AcademicYearsRouteImport.update({
  id: '/academic-years',
  path: '/academic-years',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TqiReportsIndexRoute = TqiReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TqiReportsRoute,
} as any)
const TqiReportsCreateRoute = TqiReportsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TqiReportsRoute,
} as any)
const AttendanceVolunteersRoute = AttendanceVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceStudentsRoute = AttendanceStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceHomeworkRoute = AttendanceHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceHistoryRoute = AttendanceHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AttendanceRoute,
} as any)
const AttendanceAnalyticsRoute = AttendanceAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AttendanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-years': typeof AcademicYearsRoute
  '/admins': typeof AdminsRoute
  '/advance': typeof AdvanceRoute
  '/approvals': typeof ApprovalsRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/audit-logs': typeof AuditLogsRoute
  '/cluster-dashboard': typeof ClusterDashboardRoute
  '/clusters': typeof ClustersRoute
  '/colleges': typeof CollegesRoute
  '/finance': typeof FinanceRoute
  '/homework': typeof HomeworkRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/panchayats': typeof PanchayatsRoute
  '/refunds': typeof RefundsRoute
  '/reports': typeof ReportsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/timeline': typeof TimelineRoute
  '/tqi-reports': typeof TqiReportsRouteWithChildren
  '/villages': typeof VillagesRoute
  '/volunteers': typeof VolunteersRoute
  '/attendance/analytics': typeof AttendanceAnalyticsRoute
  '/attendance/history': typeof AttendanceHistoryRoute
  '/attendance/homework': typeof AttendanceHomeworkRoute
  '/attendance/students': typeof AttendanceStudentsRoute
  '/attendance/volunteers': typeof AttendanceVolunteersRoute
  '/tqi-reports/create': typeof TqiReportsCreateRoute
  '/tqi-reports/': typeof TqiReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-years': typeof AcademicYearsRoute
  '/admins': typeof AdminsRoute
  '/advance': typeof AdvanceRoute
  '/approvals': typeof ApprovalsRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/audit-logs': typeof AuditLogsRoute
  '/cluster-dashboard': typeof ClusterDashboardRoute
  '/clusters': typeof ClustersRoute
  '/colleges': typeof CollegesRoute
  '/finance': typeof FinanceRoute
  '/homework': typeof HomeworkRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/panchayats': typeof PanchayatsRoute
  '/refunds': typeof RefundsRoute
  '/reports': typeof ReportsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/timeline': typeof TimelineRoute
  '/villages': typeof VillagesRoute
  '/volunteers': typeof VolunteersRoute
  '/attendance/analytics': typeof AttendanceAnalyticsRoute
  '/attendance/history': typeof AttendanceHistoryRoute
  '/attendance/homework': typeof AttendanceHomeworkRoute
  '/attendance/students': typeof AttendanceStudentsRoute
  '/attendance/volunteers': typeof AttendanceVolunteersRoute
  '/tqi-reports/create': typeof TqiReportsCreateRoute
  '/tqi-reports': typeof TqiReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-years': typeof AcademicYearsRoute
  '/admins': typeof AdminsRoute
  '/advance': typeof AdvanceRoute
  '/approvals': typeof ApprovalsRoute
  '/attendance': typeof AttendanceRouteWithChildren
  '/audit-logs': typeof AuditLogsRoute
  '/cluster-dashboard': typeof ClusterDashboardRoute
  '/clusters': typeof ClustersRoute
  '/colleges': typeof CollegesRoute
  '/finance': typeof FinanceRoute
  '/homework': typeof HomeworkRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/panchayats': typeof PanchayatsRoute
  '/refunds': typeof RefundsRoute
  '/reports': typeof ReportsRoute
  '/schools': typeof SchoolsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/timeline': typeof TimelineRoute
  '/tqi-reports': typeof TqiReportsRouteWithChildren
  '/villages': typeof VillagesRoute
  '/volunteers': typeof VolunteersRoute
  '/attendance/analytics': typeof AttendanceAnalyticsRoute
  '/attendance/history': typeof AttendanceHistoryRoute
  '/attendance/homework': typeof AttendanceHomeworkRoute
  '/attendance/students': typeof AttendanceStudentsRoute
  '/attendance/volunteers': typeof AttendanceVolunteersRoute
  '/tqi-reports/create': typeof TqiReportsCreateRoute
  '/tqi-reports/': typeof TqiReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-years'
    | '/admins'
    | '/advance'
    | '/approvals'
    | '/attendance'
    | '/audit-logs'
    | '/cluster-dashboard'
    | '/clusters'
    | '/colleges'
    | '/finance'
    | '/homework'
    | '/login'
    | '/notifications'
    | '/panchayats'
    | '/refunds'
    | '/reports'
    | '/schools'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/timeline'
    | '/tqi-reports'
    | '/villages'
    | '/volunteers'
    | '/attendance/analytics'
    | '/attendance/history'
    | '/attendance/homework'
    | '/attendance/students'
    | '/attendance/volunteers'
    | '/tqi-reports/create'
    | '/tqi-reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-years'
    | '/admins'
    | '/advance'
    | '/approvals'
    | '/attendance'
    | '/audit-logs'
    | '/cluster-dashboard'
    | '/clusters'
    | '/colleges'
    | '/finance'
    | '/homework'
    | '/login'
    | '/notifications'
    | '/panchayats'
    | '/refunds'
    | '/reports'
    | '/schools'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/timeline'
    | '/villages'
    | '/volunteers'
    | '/attendance/analytics'
    | '/attendance/history'
    | '/attendance/homework'
    | '/attendance/students'
    | '/attendance/volunteers'
    | '/tqi-reports/create'
    | '/tqi-reports'
  id:
    | '__root__'
    | '/'
    | '/academic-years'
    | '/admins'
    | '/advance'
    | '/approvals'
    | '/attendance'
    | '/audit-logs'
    | '/cluster-dashboard'
    | '/clusters'
    | '/colleges'
    | '/finance'
    | '/homework'
    | '/login'
    | '/notifications'
    | '/panchayats'
    | '/refunds'
    | '/reports'
    | '/schools'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/timeline'
    | '/tqi-reports'
    | '/villages'
    | '/volunteers'
    | '/attendance/analytics'
    | '/attendance/history'
    | '/attendance/homework'
    | '/attendance/students'
    | '/attendance/volunteers'
    | '/tqi-reports/create'
    | '/tqi-reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicYearsRoute: typeof AcademicYearsRoute
  AdminsRoute: typeof AdminsRoute
  AdvanceRoute: typeof AdvanceRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AttendanceRoute: typeof AttendanceRouteWithChildren
  AuditLogsRoute: typeof AuditLogsRoute
  ClusterDashboardRoute: typeof ClusterDashboardRoute
  ClustersRoute: typeof ClustersRoute
  CollegesRoute: typeof CollegesRoute
  FinanceRoute: typeof FinanceRoute
  HomeworkRoute: typeof HomeworkRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PanchayatsRoute: typeof PanchayatsRoute
  RefundsRoute: typeof RefundsRoute
  ReportsRoute: typeof ReportsRoute
  SchoolsRoute: typeof SchoolsRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRoute
  TimelineRoute: typeof TimelineRoute
  TqiReportsRoute: typeof TqiReportsRouteWithChildren
  VillagesRoute: typeof VillagesRoute
  VolunteersRoute: typeof VolunteersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteers': {
      id: '/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof VolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villages': {
      id: '/villages'
      path: '/villages'
      fullPath: '/villages'
      preLoaderRoute: typeof VillagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tqi-reports': {
      id: '/tqi-reports'
      path: '/tqi-reports'
      fullPath: '/tqi-reports'
      preLoaderRoute: typeof TqiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchayats': {
      id: '/panchayats'
      path: '/panchayats'
      fullPath: '/panchayats'
      preLoaderRoute: typeof PanchayatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework': {
      id: '/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof HomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster-dashboard': {
      id: '/cluster-dashboard'
      path: '/cluster-dashboard'
      fullPath: '/cluster-dashboard'
      preLoaderRoute: typeof ClusterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advance': {
      id: '/advance'
      path: '/advance'
      fullPath: '/advance'
      preLoaderRoute: typeof AdvanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-years': {
      id: '/academic-years'
      path: '/academic-years'
      fullPath: '/academic-years'
      preLoaderRoute: typeof AcademicYearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tqi-reports/': {
      id: '/tqi-reports/'
      path: '/'
      fullPath: '/tqi-reports/'
      preLoaderRoute: typeof TqiReportsIndexRouteImport
      parentRoute: typeof TqiReportsRoute
    }
    '/tqi-reports/create': {
      id: '/tqi-reports/create'
      path: '/create'
      fullPath: '/tqi-reports/create'
      preLoaderRoute: typeof TqiReportsCreateRouteImport
      parentRoute: typeof TqiReportsRoute
    }
    '/attendance/volunteers': {
      id: '/attendance/volunteers'
      path: '/volunteers'
      fullPath: '/attendance/volunteers'
      preLoaderRoute: typeof AttendanceVolunteersRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/students': {
      id: '/attendance/students'
      path: '/students'
      fullPath: '/attendance/students'
      preLoaderRoute: typeof AttendanceStudentsRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/homework': {
      id: '/attendance/homework'
      path: '/homework'
      fullPath: '/attendance/homework'
      preLoaderRoute: typeof AttendanceHomeworkRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/history': {
      id: '/attendance/history'
      path: '/history'
      fullPath: '/attendance/history'
      preLoaderRoute: typeof AttendanceHistoryRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/attendance/analytics': {
      id: '/attendance/analytics'
      path: '/analytics'
      fullPath: '/attendance/analytics'
      preLoaderRoute: typeof AttendanceAnalyticsRouteImport
      parentRoute: typeof AttendanceRoute
    }
  }
}

interface AttendanceRouteChildren {
  AttendanceAnalyticsRoute: typeof AttendanceAnalyticsRoute
  AttendanceHistoryRoute: typeof AttendanceHistoryRoute
  AttendanceHomeworkRoute: typeof AttendanceHomeworkRoute
  AttendanceStudentsRoute: typeof AttendanceStudentsRoute
  AttendanceVolunteersRoute: typeof AttendanceVolunteersRoute
}

const AttendanceRouteChildren: AttendanceRouteChildren = {
  AttendanceAnalyticsRoute: AttendanceAnalyticsRoute,
  AttendanceHistoryRoute: AttendanceHistoryRoute,
  AttendanceHomeworkRoute: AttendanceHomeworkRoute,
  AttendanceStudentsRoute: AttendanceStudentsRoute,
  AttendanceVolunteersRoute: AttendanceVolunteersRoute,
}

const AttendanceRouteWithChildren = AttendanceRoute._addFileChildren(
  AttendanceRouteChildren,
)

interface TqiReportsRouteChildren {
  TqiReportsCreateRoute: typeof TqiReportsCreateRoute
  TqiReportsIndexRoute: typeof TqiReportsIndexRoute
}

const TqiReportsRouteChildren: TqiReportsRouteChildren = {
  TqiReportsCreateRoute: TqiReportsCreateRoute,
  TqiReportsIndexRoute: TqiReportsIndexRoute,
}

const TqiReportsRouteWithChildren = TqiReportsRoute._addFileChildren(
  TqiReportsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicYearsRoute: AcademicYearsRoute,
  AdminsRoute: AdminsRoute,
  AdvanceRoute: AdvanceRoute,
  ApprovalsRoute: ApprovalsRoute,
  AttendanceRoute: AttendanceRouteWithChildren,
  AuditLogsRoute: AuditLogsRoute,
  ClusterDashboardRoute: ClusterDashboardRoute,
  ClustersRoute: ClustersRoute,
  CollegesRoute: CollegesRoute,
  FinanceRoute: FinanceRoute,
  HomeworkRoute: HomeworkRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PanchayatsRoute: PanchayatsRoute,
  RefundsRoute: RefundsRoute,
  ReportsRoute: ReportsRoute,
  SchoolsRoute: SchoolsRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRoute,
  TimelineRoute: TimelineRoute,
  TqiReportsRoute: TqiReportsRouteWithChildren,
  VillagesRoute: VillagesRoute,
  VolunteersRoute: VolunteersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
